<div style=" background-color: RGB(0,10,200);" >
<h1 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">PROJET 10 DATA ANALYST</h1>
<h2 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">Détectez des faux billets avec R ou Python
</h2>
<h3 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">Partie 2 : Application finale
</h3>
</div>

<div style="background-color: RGB(0,10,200);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des données </h2>
</div>

In [1]:
# Importation des librairies Pandas, Matplotlib et Numpy
import pandas as pd
import matplotlib.pyplot as plt

import plotly.express as px
import statsmodels.api as sm
import statsmodels.formula.api as smf
import scipy.stats as st
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
import numpy as np
import seaborn as sns

In [2]:
#Importation du fichier "billets_production"
billets_production=pd.read_csv('billets_production.csv')
billets_production

diagonal  height_left  height_right  margin_low  margin_up  length   id
0    171.76       104.01        103.54        5.21       3.30  111.42  A_1
1    171.87       104.17        104.13        6.00       3.31  112.09  A_2
2    172.00       104.58        104.29        4.99       3.39  111.57  A_3
3    172.49       104.55        104.34        4.44       3.03  113.20  A_4
4    171.65       103.63        103.56        3.77       3.16  113.33  A_5

In [3]:
#Importation du fichier "billets", et spécifier le bon délimiteur en ajoutant l'argument "sep"
billets=pd.read_csv('billets.csv', sep=';')
billets.head(5)

is_genuine  diagonal  height_left  height_right  margin_low  margin_up  \
0        True    171.81       104.86        104.95        4.52       2.89   
1        True    171.46       103.36        103.66        3.77       2.99   
2        True    172.69       104.48        103.50        4.40       2.94   
3        True    171.36       103.91        103.94        3.62       3.01   
4        True    171.73       104.28        103.46        4.04       3.48   

   length  
0  112.83  
1  113.09  
2  113.16  
3  113.51  
4  112.54

In [4]:
#Importation du fichier "X"
X=pd.read_csv('X.csv')



In [5]:
#Importation du fichier "Y"
Y=pd.read_csv('Y.csv')



<div style="background-color: RGB(0,10,200);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 -Simulation </h2>
</div>

<div style="border: 5px solid RGB(0,10,200);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,10,200); "> 2.1 - Simulation avec la régression logistique </a></h3>
</div>

In [6]:
#Division de la base de donnée
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=42)

In [7]:
#Création du modèle
model=LogisticRegression()
model.fit(X_train, Y_train)


C:\Users\bello\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [8]:
billets_production2=billets_production[["margin_low", "margin_up","length"]]

In [9]:
# Test model
predictions=model.predict(billets_production2)
billets_production2["Prédiction"]=predictions
billets_production2

C:\Users\bello\AppData\Local\Temp\ipykernel_30744\2503581693.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  billets_production2["Prédiction"]=predictions


margin_low  margin_up  length  Prédiction
0        5.21       3.30  111.42           0
1        6.00       3.31  112.09           0
2        4.99       3.39  111.57           0
3        4.44       3.03  113.20           1
4        3.77       3.16  113.33           1

In [10]:
billets.groupby("is_genuine").mean()

diagonal  height_left  height_right  margin_low  margin_up  \
is_genuine                                                                
False       171.90116    104.19034     104.14362    5.215935    3.35016   
True        171.98708    103.94913     103.80865    4.116097    3.05213   

               length  
is_genuine             
False       111.63064  
True        113.20243

<div style="border: 5px solid RGB(0,10,200);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,10,200); "> 2.2 - Simulation avec les k-means </a></h3>
</div>

# Kmeans avec des données train

In [11]:
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X)
labels = kmeans.labels_

In [12]:
labels

array([1, 1, 1, ..., 0, 0, 0])

In [13]:
# On peut stocker nos centroids dans une variable : 
centroidsTrain = kmeans.cluster_centers_
centroidsTrain

array([[  5.24635771,   3.34770526, 111.57208421],
       [  4.12904829,   3.06053659, 113.19122927]])

In [14]:
X["prédiction kmeans"]=labels
X

margin_low  margin_up  length  prédiction kmeans
0       4.520000       2.89  112.83                  1
1       3.770000       2.99  113.09                  1
2       4.400000       2.94  113.16                  1
3       3.620000       3.01  113.51                  1
4       4.040000       3.48  112.54                  1
...          ...        ...     ...                ...
1495    5.305269       2.93  111.21                  0
1496    5.205657       3.40  112.29                  0
1497    5.161149       3.61  110.31                  0
1498    5.171746       3.56  111.47                  0
1499    5.239567       3.24  111.49                  0

[1500 rows x 4 columns]

In [15]:
X["prédiction kmeans"].value_counts()

1    1024
0     476
Name: prédiction kmeans, dtype: int64

In [16]:
X.groupby("prédiction kmeans").mean()

margin_low  margin_up      length
prédiction kmeans                                   
0                    5.244370   3.347983  111.573319
1                    4.128881   3.060127  113.192236

# Kmeans avec des données test

In [17]:
billets_production3=billets_production[["margin_low", "margin_up","length"]]

In [18]:
kmeans = KMeans(n_clusters=len(centroidsTrain), random_state=42)
kmeans.fit(billets_production3)


KMeans(n_clusters=2, random_state=42)

In [19]:
labels

array([1, 1, 1, ..., 0, 0, 0])

In [20]:
kmeans.cluster_centers_=centroidsTrain
Predictionkmeans=kmeans.predict(billets_production3)

In [21]:
billets_production3["prédiction kmeans"]=Predictionkmeans
billets_production3

C:\Users\bello\AppData\Local\Temp\ipykernel_30744\1489945021.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  billets_production3["prédiction kmeans"]=Predictionkmeans


margin_low  margin_up  length  prédiction kmeans
0        5.21       3.30  111.42                  0
1        6.00       3.31  112.09                  0
2        4.99       3.39  111.57                  0
3        4.44       3.03  113.20                  1
4        3.77       3.16  113.33                  1

In [22]:
billets_production3.groupby("prédiction kmeans").mean()

margin_low  margin_up      length
prédiction kmeans                                   
0                       5.400   3.333333  111.693333
1                       4.105   3.095000  113.265000

In [24]:
centroidsTrain

array([[  5.24635771,   3.34770526, 111.57208421],
       [  4.12904829,   3.06053659, 113.19122927]])